### ISSUE TITLE
Mypy Pydantic support

### ISSUE THREAD

**Issue by yaleman** [yaleman/github_linter#216]
Need to add this to pyproject.toml when mypy's in the same file:

```toml

[tool.mypy]
plugins = "pydantic.mypy"
```
